version: '3.8'

services:
 nursery:
  image: node:18-alpine
  restart: always
  working_dir: /app
  ports:
   - 3000:3000
  environment:
   - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nursery
  volumes:
   - ./:/app
   - ./node_modules:/app/node_modules
  command: npm run dev

 postgres:
  image: postgres:latest
  volumes:
   - postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=postgres

 adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
 postgres: